name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: |
          echo "Setting up environment variables"
          export REACT_APP_API_KEY="${{ secrets.REACT_APP_API_KEY }}"
          export REACT_APP_AUTH_DOMAIN="${{ secrets.REACT_APP_AUTH_DOMAIN }}"
          export REACT_APP_PROJECT_ID="${{ secrets.REACT_APP_PROJECT_ID }}"
          export REACT_APP_STORAGE_BUCKET="${{ secrets.REACT_APP_STORAGE_BUCKET }}"
          export REACT_APP_MESSAGING_SENDER_ID="${{ secrets.REACT_APP_MESSAGING_SENDER_ID }}"
          export REACT_APP_APP_ID="${{ secrets.REACT_APP_APP_ID }}"
          export REACT_APP_SUPABASE_URL="${{ secrets.REACT_APP_SUPABASE_URL }}"
          export REACT_APP_SUPABASE_ANON_KEY="${{ secrets.REACT_APP_SUPABASE_ANON_KEY }}"
          export REACT_APP_DEMO="${{ secrets.REACT_APP_DEMO }}"
          echo "Environment variables set"
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./build
          keep_files: false
