name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # or your main branch name (e.g., master)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci # or yarn install

      - name: Build React app
        run: npm run build # or yarn build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v5
        with:
          branch: gh-pages # The branch where the deployment will be pushed
          folder: build # The folder containing the built website
